name: Assign Author
on:
  pull_request_target:
    types: [opened,reopened]

jobs:
  assign-author:
    if: ${{ !contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.actor],  // botチェックはjobのifに集約
            });
