"""PDR 解析パッケージの互換 facade。"""
# ruff: noqa: F401

from pathlib import Path

import pandas as pd

from ...config import (
    BACKWARD_LENGTH_SCALE,
    DATA_DIR,
    FLOORMAP_ORIGIN_PX,
    FLOORMAP_PATH,
    FLOORMAP_SCALE,
    FORWARD_HEADING_SOURCE,
    GYRO_BIAS_MIN_CALIBRATION_SECONDS,
    GYRO_BIAS_OUTLIER_MAD_SCALE,
    GYRO_BIAS_STATIC_ACCEL_P95_WEIGHT,
    GYRO_BIAS_STATIC_GYRO_STD_WEIGHT,
    GYRO_BIAS_STATIC_MAX_ACCEL_P95,
    GYRO_BIAS_STATIC_MAX_GYRO_STD,
    GYRO_BIAS_STATIC_SEARCH_END_SECONDS,
    GYRO_BIAS_STATIC_SEARCH_START_SECONDS,
    GYRO_BIAS_STATIC_WALK_ONSET_MARGIN_S,
    GYRO_BIAS_STATIC_WINDOW_SECONDS,
    GYRO_BIAS_STATIC_WINDOW_STEP_SECONDS,
    GYRO_BIAS_WALK_ONSET_MAX_INTERVAL_S,
    GYRO_BIAS_WALK_ONSET_MIN_STEPS,
    INITIAL_DIRECTION,
    K_FORWARD,
    PEAK_DISTANCE,
    PEAK_HEIGHT,
    SIDESTEP_LATERAL_RATIO,
    SIDESTEP_LENGTH_SCALE,
    SIDESTEP_MIN_LATERAL_DISPLACEMENT_M,
    SIDESTEP_SMOOTHING_METHOD,
    STEP_DETECTION_METHOD,
    STEP_VERTICAL_SMOOTH_WINDOW,
    STEP_VERTICAL_THRESHOLD_PERCENTILE,
    TURNING_LENGTH_SCALE,
    USER_HEIGHT_M,
    WINDOW_ACC,
    WINDOW_GYRO,
)
from . import pipeline as _pipeline
from .common import (
    DEVICE_ORIENTATION_MODES,
    FORWARD_HEADING_SOURCES,
    HEADING_METHODS,
    INITIAL_FORWARD_MOTION_BODY_CONSTRAINT_RAD,
    MOTION_HEADING_CORRECTION_METHODS,
    SIDESTEP_BODY_MOTION_ANGLE_THRESHOLD_RAD,
    SIDESTEP_BODY_MOTION_RATIO_THRESHOLD,
    SIDESTEP_HEADING_MAX_STEP_DELTA_RAD,
    SIDESTEP_HEADING_SOURCES,
    SIDESTEP_MOTION_LATERAL_CONSTRAINT_RAD,
    SIDESTEP_SMOOTHING_METHODS,
    SIDESTEP_STRONG_ANGLE_THRESHOLD_RAD,
    SIDESTEP_SUSPECT_MODES,
    TRAJECTORY_HEADING_MAX_STEP_DELTA_RAD,
    TURNING_SIDESTEP_HEADING_MAX_STEP_DELTA_RAD,
    _abs_angle_diff,
    _normalize_angle,
    _score_ratio,
    _validate_forward_heading_source,
    _validate_heading_method,
    _validate_motion_heading_correction,
    _validate_non_negative_parameter,
    _validate_positive_parameter,
    _validate_scale,
    _validate_sidestep_heading_source,
    _validate_sidestep_smoothing,
    _validate_sidestep_suspect_mode,
)
from .gyro_bias import (
    GYRO_BIAS_METHODS,
    _estimate_gyro_bias_initial_robust,
    _estimate_gyro_bias_prewalk_robust,
    _estimate_gyro_bias_quietest,
    _estimate_gyro_bias_static_window,
    _find_static_gyro_bias_candidate,
    _find_walk_onset_time,
    _GyroBiasStaticCandidate,
    _robust_gyro_bias_from_mask,
    _startup_static_search_range,
    _time_mask,
    _validate_gyro_bias_method,
    estimate_gyro_bias,
)
from .heading import (
    _AccelHeadingResult,
    _apply_device_orientation_to_horizontal,
    _classify_movement_type,
    _dataframe_times_or_sample_index,
    _estimate_accel_headings,
    _estimate_device_orientation_mode,
    _estimate_motion_heading_correction,
    _estimate_motion_heading_from_horizontal_accel,
    _integrate_motion_with_zero_velocity,
    _MotionHeadingResult,
    _resolve_motion_heading_correction,
    _rotate_vector,
    _select_two_accel_peaks,
    _step_segment_bounds,
    resolve_step_heading,
)
from .models import (
    GyroBiasResult,
    PreparedPdrSteps,
    StepDetectionResult,
    StepHeading,
    StepMotion,
    StepSegment,
)
from .outputs import (
    _angle_to_deg,
    _build_gyro_bias_dataframe,
    _build_step_headings_dataframe,
    _build_step_segments_dataframe,
    _build_step_vectors_dataframe,
    _build_trajectory_dataframe,
    _create_output_dir,
    _step_plot_signal,
)
from .plotting import (
    _compute_pixel_coords,
    _pixel_vector_from_heading,
    _plot_heading_overlay,
    plot_trajectory,
)
from .sensors import ACC_COLUMNS, GYRO_COLUMNS, load_sensor_data, process_sensor_data
from .sidestep import (
    _body_motion_angle_diff,
    _circular_mean_angles,
    _has_adjacent_opposite_evidence,
    _heading_change_limit_for_movement_type,
    _is_confirmed_sidestep_cluster,
    _is_sidestep_bridge_gap,
    _is_sidestep_movement,
    _is_sidestep_suspect_movement,
    _is_trajectory_sidestep_movement,
    _lateral_forward_ratio,
    _limit_heading_change,
    _mean_finite,
    _resolve_sidestep_heading,
    _resolve_world_motion_heading,
    _sidestep_body_lateral_heading,
    _sidestep_cluster_bounds,
    _sidestep_cluster_has_lateral_strength,
    _sidestep_cluster_motion_heading,
    _sidestep_cluster_motion_heading_for_indexes,
    _sidestep_direction,
    _sidestep_direction_label,
    _sidestep_evidence,
    _sidestep_motion_heading,
    _SidestepEvidence,
    _smooth_step_headings,
    _smoothed_step_displacements,
    _stabilize_trajectory_body_headings,
    _stabilize_trajectory_headings,
    _trajectory_movement_type,
    estimate_step_motion,
)
from .step_detection import (
    STEP_DETECTION_METHODS,
    _detect_steps_by_peak,
    _detect_steps_by_vertical_threshold,
    _suppress_close_contacts,
    _threshold_groups,
    _validate_step_detection_method,
    detect_step_result,
    detect_steps,
)
from .step_length import (
    _estimate_initial_forward_angle,
    estimate_step_length,
    estimate_step_length_forward,
)
from .time_utils import (
    _gyro_integration_dt,
    _sample_gyro_angle,
    _step_mid_index,
    _step_mid_time,
    _step_output_time,
    _time_at_index,
    _time_values,
)
from .trajectory import (
    estimate_trajectory,
    estimate_trajectory_with_headings,
    prepare_pdr_steps,
)

__all__ = [
    "ACC_COLUMNS",
    "BACKWARD_LENGTH_SCALE",
    "DATA_DIR",
    "DEVICE_ORIENTATION_MODES",
    "FLOORMAP_ORIGIN_PX",
    "FLOORMAP_PATH",
    "FLOORMAP_SCALE",
    "FORWARD_HEADING_SOURCE",
    "FORWARD_HEADING_SOURCES",
    "GYRO_BIAS_METHODS",
    "GYRO_BIAS_MIN_CALIBRATION_SECONDS",
    "GYRO_BIAS_OUTLIER_MAD_SCALE",
    "GYRO_BIAS_STATIC_ACCEL_P95_WEIGHT",
    "GYRO_BIAS_STATIC_GYRO_STD_WEIGHT",
    "GYRO_BIAS_STATIC_MAX_ACCEL_P95",
    "GYRO_BIAS_STATIC_MAX_GYRO_STD",
    "GYRO_BIAS_STATIC_SEARCH_END_SECONDS",
    "GYRO_BIAS_STATIC_SEARCH_START_SECONDS",
    "GYRO_BIAS_STATIC_WALK_ONSET_MARGIN_S",
    "GYRO_BIAS_STATIC_WINDOW_SECONDS",
    "GYRO_BIAS_STATIC_WINDOW_STEP_SECONDS",
    "GYRO_BIAS_WALK_ONSET_MAX_INTERVAL_S",
    "GYRO_BIAS_WALK_ONSET_MIN_STEPS",
    "GYRO_COLUMNS",
    "GyroBiasResult",
    "HEADING_METHODS",
    "INITIAL_DIRECTION",
    "INITIAL_FORWARD_MOTION_BODY_CONSTRAINT_RAD",
    "K_FORWARD",
    "MOTION_HEADING_CORRECTION_METHODS",
    "PEAK_DISTANCE",
    "PEAK_HEIGHT",
    "PreparedPdrSteps",
    "SIDESTEP_BODY_MOTION_ANGLE_THRESHOLD_RAD",
    "SIDESTEP_BODY_MOTION_RATIO_THRESHOLD",
    "SIDESTEP_HEADING_MAX_STEP_DELTA_RAD",
    "SIDESTEP_HEADING_SOURCES",
    "SIDESTEP_LATERAL_RATIO",
    "SIDESTEP_LENGTH_SCALE",
    "SIDESTEP_MIN_LATERAL_DISPLACEMENT_M",
    "SIDESTEP_MOTION_LATERAL_CONSTRAINT_RAD",
    "SIDESTEP_SMOOTHING_METHOD",
    "SIDESTEP_SMOOTHING_METHODS",
    "SIDESTEP_STRONG_ANGLE_THRESHOLD_RAD",
    "SIDESTEP_SUSPECT_MODES",
    "STEP_DETECTION_METHOD",
    "STEP_DETECTION_METHODS",
    "STEP_VERTICAL_SMOOTH_WINDOW",
    "STEP_VERTICAL_THRESHOLD_PERCENTILE",
    "StepDetectionResult",
    "StepHeading",
    "StepMotion",
    "StepSegment",
    "TRAJECTORY_HEADING_MAX_STEP_DELTA_RAD",
    "TURNING_LENGTH_SCALE",
    "TURNING_SIDESTEP_HEADING_MAX_STEP_DELTA_RAD",
    "USER_HEIGHT_M",
    "WINDOW_ACC",
    "WINDOW_GYRO",
    "_AccelHeadingResult",
    "_GyroBiasStaticCandidate",
    "_MotionHeadingResult",
    "_SidestepEvidence",
    "_abs_angle_diff",
    "_angle_to_deg",
    "_apply_device_orientation_to_horizontal",
    "_body_motion_angle_diff",
    "_build_gyro_bias_dataframe",
    "_build_step_headings_dataframe",
    "_build_step_segments_dataframe",
    "_build_step_vectors_dataframe",
    "_build_trajectory_dataframe",
    "_circular_mean_angles",
    "_classify_movement_type",
    "_compute_pixel_coords",
    "_create_output_dir",
    "_dataframe_times_or_sample_index",
    "_detect_steps_by_peak",
    "_detect_steps_by_vertical_threshold",
    "_estimate_accel_headings",
    "_estimate_device_orientation_mode",
    "_estimate_gyro_bias_initial_robust",
    "_estimate_gyro_bias_prewalk_robust",
    "_estimate_gyro_bias_quietest",
    "_estimate_gyro_bias_static_window",
    "_estimate_initial_forward_angle",
    "_estimate_motion_heading_correction",
    "_estimate_motion_heading_from_horizontal_accel",
    "_find_static_gyro_bias_candidate",
    "_find_walk_onset_time",
    "_gyro_integration_dt",
    "_has_adjacent_opposite_evidence",
    "_heading_change_limit_for_movement_type",
    "_integrate_motion_with_zero_velocity",
    "_is_confirmed_sidestep_cluster",
    "_is_sidestep_bridge_gap",
    "_is_sidestep_movement",
    "_is_sidestep_suspect_movement",
    "_is_trajectory_sidestep_movement",
    "_lateral_forward_ratio",
    "_limit_heading_change",
    "_mean_finite",
    "_normalize_angle",
    "_pixel_vector_from_heading",
    "_plot_heading_overlay",
    "_resolve_motion_heading_correction",
    "_resolve_sidestep_heading",
    "_resolve_world_motion_heading",
    "_robust_gyro_bias_from_mask",
    "_rotate_vector",
    "_sample_gyro_angle",
    "_score_ratio",
    "_select_two_accel_peaks",
    "_sidestep_body_lateral_heading",
    "_sidestep_cluster_bounds",
    "_sidestep_cluster_has_lateral_strength",
    "_sidestep_cluster_motion_heading",
    "_sidestep_cluster_motion_heading_for_indexes",
    "_sidestep_direction",
    "_sidestep_direction_label",
    "_sidestep_evidence",
    "_sidestep_motion_heading",
    "_smooth_step_headings",
    "_smoothed_step_displacements",
    "_startup_static_search_range",
    "_stabilize_trajectory_body_headings",
    "_stabilize_trajectory_headings",
    "_step_mid_index",
    "_step_mid_time",
    "_step_output_time",
    "_step_plot_signal",
    "_step_segment_bounds",
    "_suppress_close_contacts",
    "_threshold_groups",
    "_time_at_index",
    "_time_mask",
    "_time_values",
    "_trajectory_movement_type",
    "_validate_forward_heading_source",
    "_validate_gyro_bias_method",
    "_validate_heading_method",
    "_validate_motion_heading_correction",
    "_validate_non_negative_parameter",
    "_validate_positive_parameter",
    "_validate_scale",
    "_validate_sidestep_heading_source",
    "_validate_sidestep_smoothing",
    "_validate_sidestep_suspect_mode",
    "_validate_step_detection_method",
    "detect_step_result",
    "detect_steps",
    "estimate_gyro_bias",
    "estimate_step_length",
    "estimate_step_length_forward",
    "estimate_step_motion",
    "estimate_trajectory",
    "estimate_trajectory_with_headings",
    "load_sensor_data",
    "plot_trajectory",
    "prepare_pdr_steps",
    "process_sensor_data",
    "resolve_step_heading",
    "run",
]


def run(
    df_acc: pd.DataFrame | None = None,
    df_gyro: pd.DataFrame | None = None,
    plot: bool = True,
    use_particle_filter: bool = False,
    save_animation: bool | None = None,
    floormap_path: str | Path = FLOORMAP_PATH,
    origin_px: tuple[int, int] = FLOORMAP_ORIGIN_PX,
    scale: float = FLOORMAP_SCALE,
    initial_direction: float = INITIAL_DIRECTION,
    height_m: float = USER_HEIGHT_M,
    step_detection_method: str | None = None,
    heading_method: str | None = None,
    gyro_bias_method: str | None = None,
    gyro_bias: float | None = None,
    sidestep_lateral_ratio: float = SIDESTEP_LATERAL_RATIO,
    sidestep_min_lateral_displacement: float = SIDESTEP_MIN_LATERAL_DISPLACEMENT_M,
    motion_heading_correction: str = "auto",
    sidestep_smoothing: str = SIDESTEP_SMOOTHING_METHOD,
    forward_heading_source: str = FORWARD_HEADING_SOURCE,
    sidestep_heading_source: str = "motion",
    sidestep_suspect_mode: str = "motion",
) -> pd.DataFrame:
    """互換 facade 経由で PDR パイプラインを実行する。"""
    vars(_pipeline)["_create_output_dir"] = _create_output_dir
    return _pipeline.run(
        df_acc=df_acc,
        df_gyro=df_gyro,
        plot=plot,
        use_particle_filter=use_particle_filter,
        save_animation=save_animation,
        floormap_path=floormap_path,
        origin_px=origin_px,
        scale=scale,
        initial_direction=initial_direction,
        height_m=height_m,
        step_detection_method=step_detection_method,
        heading_method=heading_method,
        gyro_bias_method=gyro_bias_method,
        gyro_bias=gyro_bias,
        sidestep_lateral_ratio=sidestep_lateral_ratio,
        sidestep_min_lateral_displacement=sidestep_min_lateral_displacement,
        motion_heading_correction=motion_heading_correction,
        sidestep_smoothing=sidestep_smoothing,
        forward_heading_source=forward_heading_source,
        sidestep_heading_source=sidestep_heading_source,
        sidestep_suspect_mode=sidestep_suspect_mode,
    )
