"""旧 PDR 共通 helper import の互換 shim。"""
# ruff: noqa: F401

from ...common.lib.pdr_math import (
    INITIAL_FORWARD_MOTION_BODY_CONSTRAINT_RAD,
    SIDESTEP_BODY_MOTION_ANGLE_THRESHOLD_RAD,
    SIDESTEP_BODY_MOTION_RATIO_THRESHOLD,
    SIDESTEP_HEADING_MAX_STEP_DELTA_RAD,
    SIDESTEP_MOTION_LATERAL_CONSTRAINT_RAD,
    SIDESTEP_STRONG_ANGLE_THRESHOLD_RAD,
    TRAJECTORY_HEADING_MAX_STEP_DELTA_RAD,
    TURNING_SIDESTEP_HEADING_MAX_STEP_DELTA_RAD,
    _abs_angle_diff,
    _normalize_angle,
    _score_ratio,
    _validate_non_negative_parameter,
    _validate_positive_parameter,
    _validate_scale,
)
from ...common.lib.validation import (
    DEVICE_ORIENTATION_MODES,
    FORWARD_HEADING_SOURCES,
    HEADING_METHODS,
    MOTION_HEADING_CORRECTION_METHODS,
    SIDESTEP_HEADING_SOURCES,
    SIDESTEP_SMOOTHING_METHODS,
    SIDESTEP_SUSPECT_MODES,
)

__all__ = [
    "DEVICE_ORIENTATION_MODES",
    "FORWARD_HEADING_SOURCES",
    "HEADING_METHODS",
    "INITIAL_FORWARD_MOTION_BODY_CONSTRAINT_RAD",
    "MOTION_HEADING_CORRECTION_METHODS",
    "SIDESTEP_BODY_MOTION_ANGLE_THRESHOLD_RAD",
    "SIDESTEP_BODY_MOTION_RATIO_THRESHOLD",
    "SIDESTEP_HEADING_MAX_STEP_DELTA_RAD",
    "SIDESTEP_HEADING_SOURCES",
    "SIDESTEP_MOTION_LATERAL_CONSTRAINT_RAD",
    "SIDESTEP_SMOOTHING_METHODS",
    "SIDESTEP_STRONG_ANGLE_THRESHOLD_RAD",
    "SIDESTEP_SUSPECT_MODES",
    "TRAJECTORY_HEADING_MAX_STEP_DELTA_RAD",
    "TURNING_SIDESTEP_HEADING_MAX_STEP_DELTA_RAD",
    "_abs_angle_diff",
    "_normalize_angle",
    "_score_ratio",
    "_validate_non_negative_parameter",
    "_validate_positive_parameter",
    "_validate_scale",
]
